
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import type { CustomDatabase } from './types-custom';

const SUPABASE_URL = "https://vgkdieetxyhprrczrwfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZna2RpZWV0eHlocHJyY3pyd2ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTA0NzMsImV4cCI6MjA2MDk4NjQ3M30.hBf6Jm18Bah7PdLxn26ZTyKyJhbpndAT6aYx1leB7Nk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database & CustomDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
